# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160531_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Comment'),
        ),
    ]
