# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default='2016-06-01 19:52:53.836832'),
            preserve_default=False,
        ),
    ]
