# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='redactor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
