# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_redactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_change',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 14, 25, 9, 251614, tzinfo=utc)),
        ),
    ]
